feat: port more string functions from lodash
TinkoffCreditSystems/utils.js pull request #60
Opened 2021-05-19 17:04 UTC by alexkvak

Added `camelCaseName`, `kebabCaseName`, `snakeCaseName`, `upperFirst` and `words`.

2021-05-20 13:45 UTC, Tom910 commented on src/string/kebabCase.ts
> +const camelCaseRegex = /(\p{Lower})(\p{Upper})/gu;
это разворачивается в большие регулярки, мы можем без u модификатора реализовать?

2021-05-31 10:29 UTC, Tom910 commented on babel.config.js
> +        '@babel/plugin-proposal-unicode-property-regex',
получается, можно убрать плагин из babel конфига и тогда можно релизить. По дефолту в утилитах будет версия с юникодом и далее легаси сборки сами скомпилят

2021-05-31 16:49 UTC, meskill commented on src/string/camelCase.ts
> +const regex = /\P{L}+(.)/gu;
lodash по-другому работает, без работы с таблицей юникода: сначала символы приводятся к стандартному latin алфавиту через функцию [deburr](https://lodash.com/docs/4.17.15#deburr), разбивает по словам и потом уже эти слова склеивает вместе, что заодно и убирает всю пунктуацию.

Так вот может и тут стоит сделать также, чем возиться с юникодом? либо должны быть какие-то кейсы чтобы обрабатывать текст именно так

2021-05-31 18:21 UTC, alexkvak commented on src/string/camelCase.ts
> +const regex = /\P{L}+(.)/gu;
Так мы и не возимся, применяем современные возможности. Не хочется оглядываться на lodash, потому что у них свой подход и свои требования к среде выполнения.
Мы в этой библиотеке декларируем высокую производительность, а ее можно добиться только пожертвовав обратной совмесимостью со старыми движками.

2021-05-31 18:30 UTC, meskill commented on src/string/camelCase.ts
> +const regex = /\P{L}+(.)/gu;
как минимум сложно сказать однозначно по производительности - то что это встроенная возможность совсем не означает что оно оптимизировано или вообще концептуально может быть быстрее самописного подхода.

Даже если оставить регэкспы - смущает что поведение отличается от того же lodash - т.к. он приводит текст к стандартной таблице ASCI (приходит в голову кейсы с генерацией имён файлов или генерацией имени ключа на основании текста) и в тех случаях такое поведение обосновано, а у нас? если причины почему делаем по-другому?

2021-06-02 08:47 UTC, alexkvak commented on src/string/camelCase.ts
> +const regex = /\P{L}+(.)/gu;
Хотелось сделать функцию, которая бы умела работать с юникодом, то есть была лучшей версией функции в lodash.

Кстати, в документации к lodash не описано, что для camelCase, например, происходит замена нелатинских символов на латинские. И еще очень неочевидно то, что вырезаются знаки препинания. Если необходима и такая функция, можно сделать ее отдельной и явно комбинировать при использовании.

P.S. Проверил производительность, у моего варианта она в 2 раза ниже, чем в lodash. Изучаю пока возможные варианты.

2021-06-02 09:12 UTC, meskill commented on src/string/camelCase.ts
> +const regex = /\P{L}+(.)/gu;
угу, в lodash действительно неочевидно и потому может ввести заблуждение тех кто привык к такой логике как в lodash. Впрочем кажется сейчас большая часть либ именно так и работает как и lodash [пример](https://github.com/blakeembrey/change-case/issues/152)

поэтому хотелось бы прежде всего понять кейсы использования самих утилит, чтобы понимать какое именно поведение будет более удобным

2021-06-03 10:17 UTC, alexkvak commented on src/string/camelCase.ts
> +const regex = /\P{L}+(.)/gu;
Предназначение той или иной функции должно следовать из ее названия, поэтому и кажется правильным сделать отдельную функцию для удаления диакритических знаков и прочей не-латиницы.

2021-06-04 19:05 UTC, meskill requested changes

2021-06-04 19:05 UTC, meskill commented on src/string/__tests__/camelCaseName.ts
> +        ['Foo Bär', 'fooBR'],
давай добавим ещё тесты, что строку которая уже в нужном кейсе, не ломало.

тут например ломается в кейсе `camelCaseName('fooBar')`

2021-06-04 19:05 UTC, meskill commented on src/string/snakeCaseName.ts
> +            .replace(camelCaseRegex, (match, first, second) => `${first}-${second}`)
для kebabCaseName получилось за один replace сделать)

а тут сначала выставляется знак `-` в первом replace? а потом заменяется на `_` во втором

2021-06-08 15:14 UTC, meskill approved these changes

2021-06-08 17:25 UTC, merged